repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
    # - id: name-tests-test
    #   args: ['--django']
    - id: detect-private-key
    - id: requirements-txt-fixer

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    - id: flake8
      exclude: ^docs/|^rasa/nlu/external/

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3

-   repo: https://github.com/asottile/pyupgrade
    rev: v1.11.1
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.7

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.660
#     hooks:
#     -   id: mypy
#         language_version: python3


